name: Build

on:
  pull_request:
    paths:
      - "config/imagery/*.json"
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: "12.x"
          registry-url: https://registry.npmjs.org

      - name: Install
        run: yarn  --frozen-lockfile --check-files

      - name: Build
        run: yarn build

      - name: Lint
        run: yarn lint:ci

      - name: Format
        run: yarn lint:config && git diff --exit-code

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_BASEMAPS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_BASEMAPS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_BASEMAPS_ROLE_PROD }}

      - name: (Imagery Config) Compare to production
        if: github.ref != 'refs/heads/master' && github.event_name == 'push'
        run: |
          ./bin/basemaps-config -t production
        env:
          NODE_ENV: "production"

      # TODO: This is currently broken, the tileset is the only thing that works with tags
      # we need the imagery to work with @tags
      # - name: (Imagery Config) Create pull request tag
      #   if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
      #   run: |
      #     ./bin/basemaps-config -t pr-${{ github.event.number }} --commit
      #   env:
      #     NODE_ENV: "production"

      - name: (Imagery Config) Create production tag
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          ./bin/basemaps-config -t production --commit
        env:
          NODE_ENV: "production"
