name: build

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: linz/action-typescript@v1

      - name: Build Sprites
        run: yarn build-sprites


      - name: (NonProd) AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_NON_PROD }}
      
      - name: (NonProd - Imagery Config) Create pull request tag
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: |
          ./bin/bmc.js import -t pr-${{ github.event.number }} --commit
        
      - name: (NonProd - Imagery Config) Screenshot pull request updates
        run: |
          ./bin/bmc.js screenshot -t pr-${{ github.event.number }} --host dev.basemaps.linz.govt.nz

      - name: Save snapshots
        uses: getsentry/action-visual-snapshot@v2
        with:
          save-only: true
          snapshot-path: .artifacts/visual-snapshots

  #     # - name: (NonProd - Imagery Config) Create production tag
  #     #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
  #     #   run: |
  #     #     ./bin/bmc.js import -t production --commit
              
  #     # - name: (NonProd - Imagery Config) Screenshot updates
  #     #   if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
  #     #   run: |
  #     #     ./bin/bmc.js screenshot -t production --host dev.basemaps.linz.govt.nz

  #     # - name: (Prod) AWS Configure
  #     #   uses: aws-actions/configure-aws-credentials@v1.6.1
  #     #   with:
  #     #     aws-region: ap-southeast-2
  #     #     mask-aws-account-id: true
  #     #     role-to-assume: ${{ secrets.AWS_ROLE_PROD }}

  #     # - name: (Prod - Imagery Config) Compare to production
  #     #   if: github.ref != 'refs/heads/master' && github.event_name == 'push'
  #     #   run: |
  #     #     ./bin/bmc.js import -t production
  #     #   env:
  #     #     NODE_ENV: "production"

  #     # - name: (Prod - Imagery Config) Create pull request tag
  #     #   if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
  #     #   run: |
  #     #     ./bin/bmc.js import -t pr-${{ github.event.number }} --commit
  #     #   env:
  #     #     NODE_ENV: "production"

  #     # - name: (Prod - Imagery Config) Create production tag
  #     #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
  #     #   run: |
  #     #     ./bin/bmc.js import -t production --commit
  #     #   env:
  #     #     NODE_ENV: "production"
  visual-diff:
    permissions:
      id-token: write
      contents: write
      checks: write
    needs: [build]
    name: validate screenshots
    if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_SCREENSHOT }}
          
      - name: Diff snapshots
        id: visual-snapshots-diff
        uses: blacha/action-visual-snapshot@v2
        with:
          storage-prefix: 's3://linz-basemaps-screenshot'
          storage-url: 'https://d25mfjh9syaxsr.cloudfront.net'
