name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: linz/action-typescript@v1

      - name: Build Sprites
        run: yarn build-sprites

      - name: Check Sprites
        run: git diff --exit-code

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_BASEMAPS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_BASEMAPS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_BASEMAPS_ROLE_PROD }}

      - name: (Imagery Config) Compare to production
        if: github.ref != 'refs/heads/master' && github.event_name == 'push'
        run: |
          ./bin/basemaps-config.js -t production
        env:
          NODE_ENV: "production"

      # TODO: This is currently broken, the tileset is the only thing that works with tags
      # we need the imagery to work with @tags
      # - name: (Imagery Config) Create pull request tag
      #   if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
      #   run: |
      #     ./bin/basemaps-config.js -t pr-${{ github.event.number }} --commit
      #   env:
      #     NODE_ENV: "production"

      - name: (Imagery Config) Create production tag
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          ./bin/basemaps-config.js -t production --commit
        env:
          NODE_ENV: "production"
