name: Build

on:
  pull_request:
    paths:
      - 'config/tileset/*.json'
      - 'config/style/*.json'
  push:

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: linz/action-typescript@v1

      - name: Build Sprites
        run: yarn build-sprites


      - name: (NonProd) AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_NON_PROD }}
      
      - name: (NonProd - Imagery Config) Create pull request tag
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: |
          ./bin/bmc.js import -t pr-${{ github.event.number }} --commit
        
      - name: (NonProd - Imagery Config) Screenshot pull request updates
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: |
          ./bin/bmc.js screenshot -t pr-${{ github.event.number }} --host dev.basemaps.linz.govt.nz

      - name: (NonProd - Imagery Config) Save snapshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          save-only: true
          path: static/dev.basemaps.linz.govt.nz/

      - name: (NonProd - Imagery Config) Create production tag
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          ./bin/bmc.js import -t production --commit
              
      - name: (NonProd - Imagery Config) Screenshot updates
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: |
          ./bin/bmc.js screenshot -t production --host dev.basemaps.linz.govt.nz

      - name: (Prod) AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_PROD }}

      - name: (Prod - Imagery Config) Compare to production
        if: github.ref != 'refs/heads/master' && github.event_name == 'push'
        run: |
          ./bin/bmc.js import -t production
        env:
          NODE_ENV: "production"

      - name: (Prod - Imagery Config) Create pull request tag
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: |
          ./bin/bmc.js import -t pr-${{ github.event.number }} --commit
        env:
          NODE_ENV: "production"

      - name: (Prod - Imagery Config) Create production tag
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          ./bin/bmc.js import -t production --commit
        env:
          NODE_ENV: "production"
