name: build

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.head_ref }}
    env:
      BASEMAPS_BUCKET: linz-basemaps
      BASEMAPS_CONTAINER: ghcr.io/linz/basemaps/cli:v6.31.0-20-g96f5d669
      DOCKER_AWS_ENV: -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e AWS_REGION -e AWS_DEFAULT_REGION

    steps:
      - uses: actions/checkout@v3

      - uses: linz/action-typescript@v1

      - name: (Build) Prepare path for glyphs and sprites
        run: |
          mkdir -p assets/fonts/
          mkdir -p assets/sprites/

      - name: (Build) Build Glyphs
        uses: linz/action-build-pbf-glyphs@v1
        with:
          source: config/fonts/
          target: assets/fonts/
          
      - name: (Build) Build Sprites
        run: |
          docker run -v $PWD:$PWD ${DOCKER_AWS_ENV} ${BASEMAPS_CONTAINER} sprites --path $PWD/config/sprites/topographic/ --output $PWD/assets/sprites/
        
      - name: (Build) Bundle Assets Into Cotar
        run: |
          docker run -v $PWD:$PWD ${DOCKER_AWS_ENV} ${BASEMAPS_CONTAINER} bundle-assets --assets $PWD/assets/ --output $PWD/assets.tar.co
          ASSETS_HASH=$(ls assets*.tar.co)
          echo "ASSETS_HASH=${ASSETS_HASH}" >> $GITHUB_ENV
          echo "ASSETS_LOCATION=s3://${BASEMAPS_BUCKET}/assets/${ASSETS_HASH}" >> $GITHUB_ENV

      - name: (Build) AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_SCREENSHOT }}

      - name: Bundle Config File
        run: |
          docker run -v $PWD:$PWD ${DOCKER_AWS_ENV} ${BASEMAPS_CONTAINER} bundle --config $PWD/config --output $PWD/config.json --assets ${ASSETS_LOCATION}
          CONFIG_HASH=$(cat config.json | jq .hash -r)
          echo "CONFIG_LOCATION=s3://${BASEMAPS_BUCKET}/config/config-${CONFIG_HASH}.json.gz" >> $GITHUB_ENV
      
      - name: Upload Hashed Assets
        run: |
          aws s3 cp ${ASSETS_HASH} ${ASSETS_LOCATION}

      - name: Upload Hashed Config File
        run: |
          gzip -9 -k config.json
          aws s3 cp config.json.gz ${CONFIG_LOCATION} --content-encoding gzip

      - name: (NonProd) AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_NON_PROD }}

      - name: (NonProd - Config) Compare To DynamoDB
        run: |
          docker run -v $PWD:$PWD ${DOCKER_AWS_ENV} ${BASEMAPS_CONTAINER} import --config ${CONFIG_LOCATION}

      - name: (NonProd - Config) Import Config To DynamoDB
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          docker run -v $PWD:$PWD ${DOCKER_AWS_ENV} ${BASEMAPS_CONTAINER} import --config ${CONFIG_LOCATION} --commit

      - name: (Screenshot) Screenshot Pull Request Changes
        run: |
          docker run -v $PWD:$PWD ${DOCKER_AWS_ENV} ${BASEMAPS_CONTAINER} screenshot --config $PWD/config.json --assets $PWD/${ASSETS_HASH} --output $PWD/.artifacts/visual-snapshots

      - name: (Prod) AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_PROD }}
  
      - name: (Prod - Config) Compare to DynamoDB
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          docker run -v $PWD:$PWD ${DOCKER_AWS_ENV} ${BASEMAPS_CONTAINER} import --config ${CONFIG_LOCATION}

      - name: (Prod - Config) Import Config To DynamoDB
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          docker run -v $PWD:$PWD ${DOCKER_AWS_ENV} ${BASEMAPS_CONTAINER} import --config ${CONFIG_LOCATION} --commit

      - name: (Prod - Config) Upload Latest Assets
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          aws s3 cp ${ASSETS_HASH} s3://${BASEMAPS_BUCKET}/assets/assets-latest.tar.co

      - name: (Prod - Config) Upload Latest Config File
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          aws s3 cp config.json.gz s3://${BASEMAPS_BUCKET}/config/config-latest.json.gz --content-encoding gzip

      - name: Save snapshots
        uses: getsentry/action-visual-snapshot@v2
        with:
          save-only: true
          snapshot-path: .artifacts/visual-snapshots
        
  visual-diff:
    permissions:
      id-token: write
      contents: write
      checks: write
    needs: [build]
    name: validate screenshots
    if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v1.6.1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_SCREENSHOT }}

      - name: Diff snapshots
        id: visual-snapshots-diff
        uses: blacha/action-visual-snapshot@v2
        with:
          storage-prefix: "s3://linz-basemaps-screenshot"
          storage-url: "https://d25mfjh9syaxsr.cloudfront.net"
