name: Pull Request Action
on:
  push:
    branches:
      - feat/bot-*
jobs:
  create-pull-request:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4

      - name: pull-request
        run: |
          gh pr edit ${{ github.ref_name }} --title '${{ github.event.head_commit.message }}' --body '${{ github.event.head_commit.message }}' &&
          gh pr reopen ${{ github.ref_name }} ||
          gh pr create --base master --title '${{ github.event.head_commit.message }}' --body '${{ github.event.head_commit.message }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: [create-pull-request]
    uses: ./.github/workflows/build.yml
    secrets: inherit 
