name: Pull Request Action
on:
  push:
    branches:
      - feat/bot-*
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: pull-request
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        run: |
          gh pr create -B master -a PROJ-basemaps-dev -t "${{ github.event.head_commit.message }}" -b "${{ github.event.head_commit.message }}"
