name: Pull Request Action
on:
  push:
    branches:
      - feat/bot-*
jobs:
  create-pull-request:
    outputs:
      pr_view: ${{ steps.check_pr.outputs.pr_view }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Pull Request
        id: check_pr
        run: echo "pr_view=$(gh pr view --json url -q .url || echo "")" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        run: |
          gh pr edit ${{ github.ref_name }} --title '${{ github.event.head_commit.message }}' --body '${{ github.event.head_commit.message }}' &&
          gh pr reopen ${{ github.ref_name }} ||
          gh pr create --base master --title '${{ github.event.head_commit.message }}' --body '${{ github.event.head_commit.message }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: [create-pull-request]
    if: ${{!contains(needs.create-pull-request.outputs.pr_view, 'https://github.com/linz/basemaps-config/pull/')}}
    uses: ./.github/workflows/build.yml
    secrets: inherit
