name: Pull Request Action
on:
  push:
    branches:
      - feat/bot-*
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v3

      - name: pull-request
        run: |
          gh pr edit ${{ github.ref_name }} --title '${{ github.event.head_commit.message }}' --body '${{ github.event.head_commit.message }}' &&
          gh pr reopen ${{ github.ref_name }} ||
          gh pr create --base master --title '${{ github.event.head_commit.message }}' --body '${{ github.event.head_commit.message }}'
      
  build:
    permissions:
      id-token: write
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.head_ref }}
    env:
      BASEMAPS_BUCKET: linz-basemaps
      BASEMAPS_STAGING_BUCKET: linz-basemaps-staging
      BASEMAPS_CONTAINER: ghcr.io/linz/basemaps/cli:v6.39.0-39-gdbedf1b1
      SCREENSHOT_CONTAINER: ghcr.io/linz/basemaps-screenshot/cli:v1
      DOCKER_AWS_ENV: -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_SESSION_TOKEN -e AWS_REGION -e AWS_DEFAULT_REGION
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - uses: actions/checkout@v3

      - name: build
        uses: ./.github/workflows/build.yml
