name: "Pull Request Preview clean-up"

on:
  pull_request:
    types: [unlabeled, closed]

jobs:
  clean-up:
    concurrency: preview-${{ github.head_ref }}
    if: |
      (github.event.action == 'unlabeled' && github.event.label.name == 'preview :world_map:') ||
      (github.event.action == 'closed' && contains(github.event.pull_request.labels.*.name, 'preview :world_map:'))
    permissions:
      id-token: write
      contents: write
      deployments: write

    runs-on: ubuntu-latest
    steps:
      - name: set STAGE variable in environment for next steps
        run: echo "STAGE=Pr${{ github.event.number }}" >> $GITHUB_ENV

      - uses: linz/action-typescript@v1

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-southeast-2
          mask-aws-account-id: true
          role-to-assume: ${{ secrets.AWS_ROLE_NON_PROD }}

      - name: destroy the stack on AWS
        run: npx cdk destroy --force

      - name: update the github deployment status
        uses: bobheadxi/deployments@v1
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.STAGE }}
